# Build river and run the test suite every time a commit is pushed to master or
# a pull request is opened against master.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: voidlinux

jobs:
  default_build:
    name: default build
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest

    steps:
      - name: install deps
        run: |
          xbps-install -S
          xbps-install -uy xbps
          xbps-install -uy zig wayland-devel wayland-protocols wlroots-devel \
          	libxkbcommon-devel pixman-devel pkgconf scdoc git

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          zig build

      - name: test
        run: |
          zig build test

  xwayland_build:
    name: xwayland build
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest

    steps:
      - name: install deps
        run: |
          xbps-install -S
          xbps-install -uy xbps
          xbps-install -uy
          xbps-install -uy zig wayland-devel wayland-protocols wlroots-devel \
          	libxkbcommon-devel pixman-devel pkgconf scdoc git

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          zig build -Dxwayland=true

      - name: test
        run: |
          zig build -Dxwayland=true test

  zig_fmt:
    name: zig fmt
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest

    steps:
      - name: install deps
        run: |
          xbps-install -S
          xbps-install -uy xbps
          xbps-install -uy
          xbps-install -uy zig git

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: fmt
        run: |
          zig fmt --check river/
          zig fmt --check riverctl/
          zig fmt --check rivertile/
          zig fmt --check example/
